#!/bin/bash

#PBS -o /home/aeurai/jobs
#PBS -e /home/aeurai/jobs
#PBS -lnodes=1 -lwalltime=01:00:00

cd $PBS_O_WORKDIR

# load necessary modules
module load matlab
# module load python/2.7.9 # has HDDM installed

matlab -nodesktop -nodisplay -r "HDDM_readIntoMatlab; exit;"
