#!/bin/bash

#PBS -o /home/aeurai/jobs
#PBS -e /home/aeurai/jobs
#PBS -lnodes=1 -lwalltime=01:00:00

# load necessary modules
module load stopos
source activate python27 # use anaconda

# determine how many parallel jobs we can run on this node
# ncores=`sara-get-num-cores`
# ((ncores -= 1)) # subtract one for system processes
ncores=1 # for some reason the getnumcores fails
echo "ncores = $ncores"

# loop over the cores available
for ((i=1; i<=ncores; i++)) ; do
(

  for ((j=1; j<=1; j++)) ; do
     stopos next -p pool2
       if [ "$STOPOS_RC" != "OK" ]; then
        break
     fi
    echo "Running with parameters: $STOPOS_VALUE"

    # see https://userinfo.surfsara.nl/systems/lisa/software/stopos
    a=( $STOPOS_VALUE )
    d=${a[0]}
    v=${a[1]}

    # first, run the model
 	  eval "python /home/aeurai/code/RT_RDK/b1_HDDM_run.py -r 0 -d $d -v $v"

    stopos remove -p pool2
stopos status -p pool2
   done
 ) &
done
wait
