#!/bin/bash

#PBS -o /home/aeurai/jobs
#PBS -e /home/aeurai/jobs
#PBS -lwalltime=10:00:00
#PBS -lnodes=1:mem64gb

# load necessary modules
source activate python27 # use anaconda

python /home/aeurai/code/RT_RDK/b1_HDDM_run.py -r 1 -d 1 -v 7 -i 14
