#!/bin/bash

#PBS -o /home/aeurai/jobs
#PBS -e /home/aeurai/jobs
#PBS -lnodes=1 -lwalltime=01:00:00

# run in the current working (submission) directory
cd $PBS_O_WORKDIR

# load necessary modules
module load matlab
matlab -nodesktop -nodisplay -r "disp(pwd); e0_plotAll; exit"

