#!/bin/bash

#SBATCH -t 5-00:00 # maximum 5 days on cartesius. Acceptable time formats include "minutes", "minutes:seconds", "hours:minutes:seconds", "days-hours", "days-hours:minutes" and "days-hours:minutes:seconds".
#SBATCH -N 1
#SBATCH -o /home/aeurai/jobs/slurm-%A_%a.out
#SBATCH -e /home/aeurai/jobs/slurm-%A_%a.err
#SBATCH --mail-user=anne.urai@gmail.com
#SBATCH --mail-type=END,FAIL

# load necessary modules
module load stopos
source activate python27 # use anaconda

# determine how many parallel jobs we can run on this node
ncores=`sara-get-num-cores` # 16 in total on LISA normal nodes
((ncores -= 1)) # subtract one for system processes, will have 15
echo "ncores = $ncores"

# loop over the cores available
for ((i=1; i<=ncores; i++)) ; do
(

  for ((j=1; j<=1; j++)) ; do
     stopos next -p pool
       if [ "$STOPOS_RC" != "OK" ]; then
        break
     fi
    echo "Running with parameters: $STOPOS_VALUE"

    # see https://userinfo.surfsara.nl/systems/lisa/software/stopos
    a=( $STOPOS_VALUE )
    d=${a[0]}
    v=${a[1]}
    i=${a[2]}
    s=${a[3]}

    # first, run the model
 	  eval "python /home/aeurai/code/serialDDM/fitHDDM.py -r 1 -d $d -v $v -i $i -s $s"

    stopos remove -p pool
stopos status -p pool
   done
 ) &
done
wait

# echo "Job $PBS_JOBID finished at `date`" | mail $USER -s "Job $PBS_JOBID"

