#!/bin/bash

#SBATCH -t 5-00:00:00 # maximum 5 days on cartesius
#SBATCH -n 1
#SBATCH -o /home/aeurai/jobs/slurm-%A_%a.out
#SBATCH -e /home/aeurai/jobs/slurm-%A_%a.err
#SBATCH -p normal

# load necessary modules
module load stopos
module load python/2.7.9 # has HDDM installed

# determine how many parallel jobs we can run on this node
ncores=`sara-get-num-cores`

# loop over the cores available
for ((i=1; i<=ncores; i++)) ; do
(

  for ((j=1; j<=1; j++)) ; do
     stopos next -p poolhddm
       if [ "$STOPOS_RC" != "OK" ]; then
        break
     fi
    echo "Running with parameters: $STOPOS_VALUE"

    # see https://userinfo.surfsara.nl/systems/lisa/software/stopos
    a=( $STOPOS_VALUE )
    v=${a[0]}
    i=${a[1]}

    # first, run the model
 	  eval "python /home/aeurai/code/MEG/Behaviour/HDDM_RunStopos.py -v $v -i $i"

    stopos remove -p poolhddm
stopos status -p poolhddm
   done
 ) &
done
wait
